service: autoservice-lambda-auth
frameworkVersion: '3'

provider:
  name: aws
  runtime: python3.11
  region: ${env:AWS_REGION, 'us-east-1'}
  stage: ${opt:stage, 'dev'}
  role: arn:aws:iam::251858421017:role/LabRole
  environment:
    JWT_SECRET: ${env:JWT_SECRET, 'change-me'}
    JWT_ISSUER: ${env:JWT_ISSUER, 'autoservice-auth'}
    JWT_EXPIRES_SECONDS: ${env:JWT_EXPIRES_SECONDS, '3600'}
    LOG_LEVEL: ${env:LOG_LEVEL, 'INFO'}
    DB_HOST: ${env:DB_HOST, ''}
    DB_NAME: ${env:DB_NAME, ''}
    DB_USER: ${env:DB_USER, ''}
    DB_PASSWORD: ${env:DB_PASSWORD, ''}
    DB_PORT: ${env:DB_PORT, '5432'}
    DD_API_KEY: ${env:DD_API_KEY, ''}
    DD_SITE: ${env:DD_SITE, 'datadoghq.com'}
    DD_ENV: ${self:provider.stage}
    DD_SERVICE: autoservice-lambda-auth
    DD_TRACE_ENABLED: ${env:DD_TRACE_ENABLED, 'false'}
    DD_LOGS_INJECTION: 'true'

functions:
  authCpf:
    name: cpf-auth
    handler: src/lambda_function.handler
    disableLogs: true
    layers:
      - arn:aws:lambda:${aws:region}:464622532012:layer:Datadog-Python311:115
      - arn:aws:lambda:${aws:region}:464622532012:layer:Datadog-Extension:74
    events:
      - http:
          path: /auth/cpf
          method: post
          cors: true

package:
  individually: false
  patterns:
    - '!**'
    - 'src/**'
    - 'requirements.txt'

plugins:
  - serverless-python-requirements

custom:
  pythonRequirements:
    dockerizePip: false
    stripEssentials: true
    zip: false