service: autoservice-lambda-auth
frameworkVersion: '3'

provider:
  name: aws
  runtime: python3.11
  region: ${env:AWS_REGION, 'us-east-1'}
  stage: ${opt:stage, 'dev'}
  role: arn:aws:iam::251858421017:role/LabRole
  disableLogs: true
  environment:
    JWT_SECRET: ${env:JWT_SECRET, 'change-me'}
    JWT_ISSUER: ${env:JWT_ISSUER, 'autoservice-auth'}
    JWT_EXPIRES_SECONDS: ${env:JWT_EXPIRES_SECONDS, '3600'}
    DATADOG_API_KEY: ${env:DATADOG_API_KEY, ''}
    DATADOG_SITE: ${env:DATADOG_SITE, 'datadoghq.com'}
    LOG_LEVEL: ${env:LOG_LEVEL, 'INFO'}
  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - logs:CreateLogGroup
            - logs:CreateLogStream
            - logs:PutLogEvents
          Resource: '*'

functions:
  authCpf:
    name: cpf-auth
    handler: src/lambda_function.handler
    events:
      - http:
          path: /auth/cpf
          method: post
          cors: true

package:
  patterns:
    - '!**/**'
    - 'src/**'
    - 'requirements.txt'

plugins:
  - serverless-python-requirements

custom:
  pythonRequirements:
    dockerizePip: false
    stripEssentials: true
